---
#- name: Installing bridge-utils
#  apt: name=bridge-utils state=present

- name: Creating virtual interface veth0
  shell: ip link show veth0 || ip link add type veth peer

#- name: Creating a bridge
#  shell: brctl show | grep br0 || brctl addbr br0
#
#- name:  Setting IP {{ neutron_external_address }} for veth0
#  shell: ip addr show | grep {{ neutron_external_address }} || ip addr add {{ neutron_external_address }} dev veth0
#
#- name: Turning veth0 up
#  shell: ip link set veth0 up
#
#- name: Turning veth1 up
#  shell: ip link set veth1 up
#
#- name: Connecting veth1 to br0
#  shell: brctl addif br0 eth0
#
#- name: Connecting eth0 to br0
#  shell: brctl addif br0 veth1
#
#- name: Turning br0 up
#  shell: ifconfig br0 up
